apiVersion: v1
kind: Service
metadata:
  name: ss-app-service
spec:
  selector:
    app: ss-app
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010  # Replace with the port your application listens on
  type: ClusterIP